version: '3.7'

networks:
  microservices:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    networks:
      - microservices

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    container_name: grafana
    networks:
      - microservices

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    container_name: zipkin
    networks:
      - microservices

  mysql:
    image: mysql
    ports:
      - "13306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpwd
    networks:
      - microservices