/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.jar.service.system.common.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ApplicationStatus implements org.apache.avro.generic.GenericEnumSymbol<ApplicationStatus> {
  PENDING, STARTED, SAVED, CONTAINERIZING, COMPLETE, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ApplicationStatus\",\"namespace\":\"com.jar.service.system.common.avro.model\",\"symbols\":[\"PENDING\",\"STARTED\",\"SAVED\",\"CONTAINERIZING\",\"COMPLETE\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
