/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.jar.service.system.common.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ContainerStatus implements org.apache.avro.generic.GenericEnumSymbol<ContainerStatus> {
  INITIALIZED, STARTED, STOPPED, DELETED, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ContainerStatus\",\"namespace\":\"com.jar.service.system.common.avro.model\",\"symbols\":[\"INITIALIZED\",\"STARTED\",\"STOPPED\",\"DELETED\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
