/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.jar.service.system.common.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum MessageType implements org.apache.avro.generic.GenericEnumSymbol<MessageType> {
  CREATE, DELETE, FAIL, REJECT, UPDATE, NO_DEF  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MessageType\",\"namespace\":\"com.jar.service.system.common.avro.model\",\"symbols\":[\"CREATE\",\"DELETE\",\"FAIL\",\"REJECT\",\"UPDATE\",\"NO_DEF\"],\"default\":\"NO_DEF\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
